name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: "build internal packages for linting"
        run: pnpm --filter "@rijkshuisstijl-community/design-tokens" build

      - name: "Continuous Integration: lint"
        run: pnpm run --if-present lint

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: "Continuous Integration: build"
        env:
          BASE_URL: "/utrecht/"
        run: pnpm run --if-present build

      # Due to dependency on type definitions, typechecking must be done after build
      - name: "Continuous Integration: typecheck"
        run: pnpm run --if-present typecheck

      - name: "Retain build artifact: Storybook"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: storybook
          path: packages/storybook/dist/
          retention-days: 1

      - name: "Retain build artifact: CSS"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: css
          path: packages/components-css/dist/

      - name: "Retain build artifact: React"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: react
          path: packages/components-react/dist/    

      - name: "Retain build artifact: Storybook Angular"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: storybook-angular
          path: packages/storybook-angular/dist/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: "Restore build artifact: Storybook"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: storybook
          path: packages/storybook/dist/

      - name: "Restore build artifact: Storybook Angular"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: storybook-angular
          path: packages/storybook-angular/dist/

      - name: "Restore build artifact: CSS"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: css
          path: packages/components-css/dist/

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: "Continuous Integration: test"
        run: pnpm run --if-present test

      - name: Publish to Chromatic
        uses: chromaui/action@4c20b95e9d3209ecfdf9cd6aace6bbde71ba1694 # 13.3.4
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          autoAcceptChanges: main
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: packages/storybook/dist/
          exitOnceUploaded: true

      - name: Publish to Chromatic
        uses: chromaui/action@4c20b95e9d3209ecfdf9cd6aace6bbde71ba1694 # 13.3.4
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          autoAcceptChanges: main
          projectToken: ${{ secrets.ANGULAR_CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: packages/storybook-angular/dist/
          exitOnceUploaded: true

  test-example-applications:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout branch
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Install pnpm package manager
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Set up Node.js version
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: "Restore build artifact: CSS"
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: css
        path: packages/components-css/dist/

    - name: "Restore build artifact: React"
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: react
        path: packages/components-react/dist/
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm test:e2e

    - name: Upload report  
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7

  publish-website:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout release branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Restore build artifact: Storybook"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: storybook
          path: packages/storybook/dist/

      - name: Continuous Deployment to GitHub Pages
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: packages/storybook/dist/

  test-a11y:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: "Restore build artifact: Storybook"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: storybook
          path: packages/storybook/dist/

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: "Accessibility tests Storybook"
        run: pnpm test-storybook:ci

  check-changeset:
    runs-on: ubuntu-latest
    needs: install
    if: github.event_name == 'pull_request' && github.actor != 'nl-design-system-ci'

    steps:
      - name: Checkout branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for missing changeset
        run: pnpm changeset status --since=origin/main

  publish-npm:
    runs-on: ubuntu-latest
    needs: [lint, test, test-example-applications]
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: publish

    permissions:
      id-token: write

    steps:
      - name: Checkout release branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js version
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc

      - name: "Continuous Deployment: install"
        run: pnpm install --frozen-lockfile

      - name: "Continuous Deployment: build"
        run: pnpm run --if-present build

      - name: Set up Node.js that is compatible with OIDC
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24

      - name: "Continuous Deployment: update versions and publish to NPM"
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          commit: "docs(release): design system packages"
          setupGitUser: false
          title: "docs(release): design system packages"
          publish: "pnpm run publish:changeset"
